FROM python:3.11-slim

WORKDIR /app

COPY backend/auth_service/ .

RUN pip install --no-cache-dir \
    fastapi uvicorn sqlalchemy \
    psycopg2-binary python-jose \
    bcrypt python-dotenv pydantic

EXPOSE 8001

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]
